[package]
name = "test-candle-onnx"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { version = "0.8.4" }
candle-onnx = "0.8.4"
image = "0.25.6"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rubato = "0.16.2"
